name: 'Clean workspace and Checkout'
description: 'clean workspace and checkout'
runs:
  using: "composite"
  steps:
    - uses: AutoModality/action-clean@v1 # must clean workspace
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Print message
      run: |
        echo 'abccccc'
