name: int_test_env

permissions: write-all

#test-g-01
#test-merge-p-001-feature-01-01
on:  
  schedule:
    # Daily 19:30 UTC + 8:00
    - cron:  '25 13 * * *'
  #test-d-03
  push:
    branches:
        - master
        - '**'
  # only support manually triggering1
  workflow_dispatch:

concurrency: 
  # if the workflow have same concurrency group, previous one will be cancel
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true      

jobs:
  print-group:
    runs-on: [ubuntu-latest]
    steps:
      - name: group print
        run: |
          echo 'group print'
          echo ${{ github.workflow }}-${{ github.ref }}

  checkout-SCM:
    runs-on: [ubuntu-latest]
    steps:
      - name: SCM-check start
        run: |
          echo 'checkout-SCM start'
          echo $(date +'%Y-%m-%dT%H:%M:%S')
      - uses: AutoModality/action-clean@v1 # must clean workspace
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
  environment-check:
    needs: checkout-SCM
    runs-on: [ubuntu-latest]
    steps:
      - name: env-check start
        run: |
      - uses: AutoModality/action-clean@v1 # must clean workspace
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    echo 'env-check start'
      - uses: ./.github/actions/clean-workspace-and-checkout
        id: clean-workspace-and-checkout
  post-actions:
    needs: environment-check
    runs-on: [ubuntu-latest]
    steps:
      - name: post-actions
        run: |
          echo 'post-actions start'
      - name: Run int test env
        run: |
          echo "go go test"
      - name: Successful
        if: ${{ success() }}
        run: |
          echo 'int test env success.'
          #cat << EOF > /tmp/Fortify_result.json
          #{ 
          #"to":"woodfealutor@gmail.com", 
          #"subject":"[int test env] SUCCESSFUL: XDRTH/XDRTH-Fortify-${{ github.run_number }}", 
          #"message":"Project: XDRTH/XDRTH-Fortify <br>Build Number: ${{ github.run_number }} " 
          #}
          #EOF
          #curl -X POST $CI_SENDMAIL -H "Content-Type: application/json" --data-binary "@/tmp/Fortify_result.json"
      - name: Failed
        if: ${{ failure() }}
        run: |
          echo 'int test env failed.'
          #cat << EOF > /tmp/Fortify_result.json
          #{ 
          #"to":"woodfealutor@gmail.com", 
          #"subject":"[int test env] FAILED: XDRTH/XDRTH-Fortify-${{ github.run_number }}", 
          #"message":"Project: XDRTH/XDRTH-Fortify <br>Build Number: ${{ github.run_number }}" 
          #}
          #EOF
          #curl -X POST $CI_SENDMAIL -H "Content-Type: application/json" --data-binary "@/tmp/Fortify_result.json"
  int-test-env-flow:
    runs-on: [ubuntu-latest]
    steps:
      - name: print variable
        run: |
          echo "Build flow"
          echo " github.action  - "${{ github.action }}
          echo " github.action_path  - "${{ github.action_path }}
          echo " github.ACTION_REPOSITORY  - "${{ github.ACTION_REPOSITORY }}
          echo " github.ACTIONS  - "${{ github.ACTIONS }}
          echo " github.ACTOR  - "${{ github.ACTOR }}
          echo " github.API_URL  - "${{ github.API_URL }}
          echo " github.BASE_REF  - "${{ github.BASE_REF }}
          echo " github.ENV " - ${{ github.ENV }}
          echo " github.EVENT_NAME  - "${{ github.EVENT_NAME }}
          echo " github.EVENT_PATH  - "${{ github.EVENT_PATH }}
          echo " github.GRAPHQL_URL  - "${{ github.GRAPHQL_URL }}
          echo " github.HEAD_REF  - "${{ github.HEAD_REF }}
          echo " github.JOB  - "${{ github.JOB }}
          echo " github.PATH  - "${{ github.PATH }}
          echo " github.REF  - "${{ github.REF }}
          echo " github.REF_NAME  - "${{ github.REF_NAME }}
          echo " github.GITHUB_REF_NAME  - "${{ github.GITHUB_REF_NAME }}
          echo " github.REF_TYPE   - "${{ github.REF_TYPE }} 
          echo " github.REPOSITORY  - "${{ github.REPOSITORY }}
          echo " github.REPOSITORY_OWNER  - "${{ github.REPOSITORY_OWNER }}
          echo " github.RETENTION_DAYS  - "${{ github.RETENTION_DAYS }}
          echo " github.RUN_ATTEMPT   - "${{ github.RUN_ATTEMPT }} 
          echo " github.RUN_ID  - "${{ github.RUN_ID }}
          echo " github.RUN_NUMBER  - "${{ github.RUN_NUMBER }}
          echo " github.SERVER_URL   - "${{ github.SERVER_URL }} 
          echo " github.SHA  - "${{ github.SHA }}
          echo " github.STEP_SUMMARY  - "${{ github.STEP_SUMMARY }}
          echo " github.WORKSPACE  - "${{ github.WORKSPACE }}
          echo " runner.ARCH  - "${{ runner.ARCH }}
          echo " runner.NAME  - "${{ runner.NAME }}
          echo " github.OS  - "${{ github.OS }}
          echo " github.TEMP  - "${{ github.TEMP }}
          echo " runner.TOOL_CACHE  - "${{ runner.TOOL_CACHE }}
          echo "BUILD_VERSION_RAW = "v${{github.RUN_NUMBER}}-${{ github.REF_NAME }}-az
          echo "GIT_ORIGIN = "${{github.SERVER_URL}}
          echo "github.event.number = "${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
      - name: print flow
        run: |
          echo "Int test env flow"
      
